export const FETCH_SUBSCRIPTION_REQUESTED = "FETCH_SUBSCRIPTION_REQUESTED";
export const FETCH_SUBSCRIPTION_SUCCESS = "FETCH_SUBSCRIPTION_SUCCESS";
export const FETCH_SUBSCRIPTION_FAIL = "FETCH_SUBSCRIPTION_FAIL";

export const ADD_SUBSCRIPTION_REQUESTED = "ADD_SUBSCRIPTION_REQUESTED";
export const ADD_SUBSCRIPTION_SUCCESS = "ADD_SUBSCRIPTION_SUCCESS";
// export const ADD_SUBSCRIPTION_FAIL = "ADD_SUBSCRIPTION_FAIL";

export const REMOVE_SUBSCRIPTION_REQUESTED = "REMOVE_SUBSCRIPTION_REQUESTED";
export const REMOVE_SUBSCRIPTION_SUCCESS = "REMOVE_SUBSCRIPTION_SUCCESS";
// export const REMOVE_SUBSCRIPTION_FAIL = "REMOVE_SUBSCRIPTION_FAIL";
