export const FETCH_TASK_REQUESTED = "FETCH_TASK_REQUESTED";
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAIL = "FETCH_TASK_FAIL";

export const CREATE_TASK_REQUESTED = "CREATE_TASK_REQUESTED";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";

export const UPDATE_TASK_REQUESTED = "UPDATE_TASK_REQUESTED";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const DELETE_TASK_REQUESTED = "DELETE_TASK_REQUESTED";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";
